services:
  - type: web
    name: student-expense-tracker
    runtime: docker
    plan: free
    region: singapore
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: DB_URL
        fromDatabase:
          name: student-expenses-db
          property: connectionString

      - key: DB_DRIVER_CLASS_NAME
        value: org.postgresql.Driver

      - key: DB_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect

      - key: APP_PASSWORD
        value: "123456"

databases:
  - name: student-expenses-db
    plan: free
    region: singapore
    databaseName: student_expenses
    user: student_expenses_user