spring.application.name=student-expense-tracker

# Database
# Local default: MySQL
# Render: PostgreSQL
spring.datasource.url=jdbc:${DB_DRIVER:mysql}://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:student_expenses}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:mysql}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

server.port=${PORT:8080}